name: Deploy to GitHub Pages

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace secrets in HTML
      run: |
        sed -i 's/__STRAVA_CLIENT_ID__/${{ secrets.STRAVA_CLIENT_ID }}/g' index.html
        sed -i 's#__API_GATEWAY_URL__#${{ secrets.API_GATEWAY_URL }}#g' index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
